# External gems
gems:
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: Escrever para aprender...
subtitle: "Um blog para escrever sobre JS ou tudo o que eu aprender em desenvolvimento <3"
email: hello@nathpaiva.com.br
name: Nath Paiva
description: >
  Um blog para escrever sobre JS ou tudo o que eu aprender em desenvolvimento <3.

# Base URL
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nathfpaiva.github.io" # the base hostname & protocol for your site
cover: "/assets/header_image_nath.jpg"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Disqus comments
disqus_shortname: nathpaiva

links:
  - title: Sobre mim
    url: /sobre
  - title: Tags
    url: /tags

social:
  - name: Twitter
    icon: twitter
    username: NathPaiva
    url: https://twitter.com/NathPaiva
    desc: Follow me on Twitter
    share: true

  - name: GitHub
    icon: github
    username: nathpaiva
    url: https://github.com/nathpaiva
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Nath Paiva
    url: https://www.linkedin.com/in/nathalia-paiva-front-end/?locale=en_US
    desc: Connect with me on LinkedIn
    share: true

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/nathpaiva/nathpaiva.github.io"
    os_rcs_type: "git"
    os_src: "git@github.com:nathpaiva/nathpaiva.github.io.git"
